# Generated by Django 3.0.3 on 2020-03-09 06:11

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prouser',
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='prouser',
            name='activation_key',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='prouser',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
