# Generated by Django 3.0.3 on 2020-03-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200309_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prouser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='prouser',
            name='email_validated',
        ),
    ]
