# Generated by Django 3.0.3 on 2020-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catag_name', models.CharField(max_length=100)),
                ('catag_slug', models.SlugField(blank=True, max_length=100, verbose_name='catag slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
